### ISSUE TITLE
Can't find file config.yaml

### ISSUE THREAD

**Issue by chen10089** [vsomnath/graphretro#12]
(seq_gr) [mahaohui@gpu004 graphretro]$ python scripts/eval/single_edit_lg.py --edits_exp offline-run-20241107_145738-mi48ov1i --edits_step best_model  --lg_exp offline-run-20241108_113547-u73ybbp4 --lg_step best_model --exp_dir experiments
Traceback (most recent call last):
  File "scripts/eval/single_edit_lg.py", line 180, in <module>
    main()
  File "scripts/eval/single_edit_lg.py", line 104, in main
    edits_loaded, edit_net_name = load_edits_model(args)
  File "scripts/eval/single_edit_lg.py", line 48, in load_edits_model
    with open(f"{args.exp_dir}/wandb/{args.edits_exp}/files/config.yaml", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/wandb/offline-run-20241107_145738-mi48ov1i/files/config.yaml'

After train model: 
python scripts/benchmarks/run_model.py --config_file configs/single_edit/defaults.yaml 
python scripts/benchmarks/run_model.py --config_file configs/lg_ind/defaults.yaml 

I get this two wandb folder， but when I eval the model get this error, what can I do?

**Comment by chen10089** [comment]
I solved the problem by set wandb API key.
